<?php

namespace app\admin\controller;

use app\common\controller\BaseController;


/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/1/11
 * Time: 9:51
 */
class Super extends BaseController
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!session('username')) {
            $this->error('请先登录系统', 'login/index');
        }
    }
}