<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/1/10
 * Time: 18:03
 */

namespace app\index\controller;


use think\Controller;

class Super extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->top();
        $this->right();
    }

    /**
     * 页面上边的布局
     */
    public function top()
    {
        $cateres = db('cates')->order('id desc')->select();

        $this->assign(array('cateres' => $cateres));
    }

    /**
     * 页面的右边布局
     */
    public function right()
    {
        // 标签列表
        $tagres = db('tags')->order('id desc')->select();

        // 用户点击数排行前八的文章
        $clickres = db('article')->order('click desc')->limit(8)->select();

        // 推荐的文章列表
        $tjres = db('article')->where('state', '=', 1)->order('click desc')->limit(8)->select();


        $this->assign(array('tagres' => $tagres, 'clickres' => $clickres, 'tjres' => $tjres));
    }

}